"""empty message

Revision ID: 110fdf7dd36b
Revises: 45b4b8997aae
Create Date: 2022-06-07 11:03:33.689511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110fdf7dd36b'
down_revision = '45b4b8997aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
