"""empty message

Revision ID: 35683577a5dc
Revises: 4e786fd22231
Create Date: 2022-06-05 16:05:19.833090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35683577a5dc'
down_revision = '4e786fd22231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
